update man page; fix shell redirect; create example rcfile if missing
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@18460 06827809-a52a-0410-b366-d66718629ded

diff --git a/local/mib2c-update b/local/mib2c-update
--- a/local/mib2c-update
+++ b/local/mib2c-update
@@ -39,7 +39,7 @@ debug()
 
 error()
 {
-    echo "ERROR: $@" >2
+    echo "ERROR: $@" >&2
 }
 
 die()
@@ -310,6 +310,14 @@ fi
 
 if [ -f .mib2c-updaterc ]; then
     . .mib2c-updaterc
+else
+   echo "creating example .mib2c-udpaterc. edit as needed and re-run "
+   echo "mib2c-update."
+   
+   echo "UPDATE_OID=ipAddressTable" >> .mib2c-updaterc
+   echo "UPDATE_CONF=mib2c.mfd.conf" >> .mib2c-updaterc
+   echo "UPDATE_MIB2C_OPTS=" >> .mib2c-updaterc
+   echo "#UPDATE_NOPROBE=1" >> .mib2c-updaterc
 fi
 
 check_setup
