autoconf
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@6551 06827809-a52a-0410-b366-d66718629ded

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1245,7 +1245,7 @@ fi
 
 
 if test "x$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "x"; then
-  if test "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "1" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2c" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "3"; then
+  if test "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "1" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "3"; then
     { echo "configure: error: Illegal version number passed to --with-default-snmp-version" 1>&2; exit 1; }
   fi
 fi
@@ -16495,8 +16495,8 @@ EOF
 fi
 
 
-if test "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "1" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2c" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "3"; then
-  { echo "configure: error: Illegal version number.  Only 1, 2c and 3 are supported." 1>&2; exit 1; }
+if test "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "1" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "2" -a "$ac_cv_user_prompt_DEFAULT_SNMP_VERSION" != "3"; then
+  { echo "configure: error: Illegal version number.  Only 1, 2 (for SNMPv2c) and 3 are supported." 1>&2; exit 1; }
 fi
 
 
