This commit was manufactured by cvs2svn to create tag 'Ext-5-2-4-pre2'.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/tags/Ext-5-2-4-pre2@15913 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/agent/mibgroup/versiontag b/net-snmp/agent/mibgroup/versiontag
--- a/net-snmp/agent/mibgroup/versiontag
+++ b/net-snmp/agent/mibgroup/versiontag
@@ -1,9 +1,5 @@
 #!/bin/sh
 
-if [ "x$CVSUSER" = "x" ] ; then
-  CVSUSER=hardaker
-fi
-
 DOIT=
 
 if [ $2 = "tag" -o $2 = "tar" ];
@@ -14,7 +10,7 @@ else
     case "$1" in
     Ext*) ;;
     *)  echo "VERSION must begin with Ext"
-        exit 0 ;;
+        exit 1 ;;
     esac
 
     VERSION="$1"
@@ -22,13 +18,25 @@ else
 fi
 
 if [ $2 = "tag" ]; then
-    $DOIT cvs tag $VERSIONTAG
+    echo "ERROR: tagging is now handled by the 'makerelease' script."
+    exit 1
 fi
 
 if [ $2 = "tar" ]; then
-    $DOIT cvs -d $CVSUSER@cvs.sourceforge.net:/cvsroot/net-snmp export -d net-snmp-$VERSION -r $VERSIONTAG net-snmp
+    if [ -d CVS ]; then
+        $DOIT cvs export -d net-snmp-$VERSION -r $VERSIONTAG net-snmp
+    else
+        if [ "x$CVSUSER" = "x" ] ; then
+          CVSUSER=hardaker
+        fi
+        $DOIT cvs -d $CVSUSER@net-snmp.cvs.sourceforge.net:/cvsroot/net-snmp export -d net-snmp-$VERSION -r $VERSIONTAG net-snmp
+    fi
     $DOIT net-snmp-$VERSION/remove-files net-snmp-$VERSION
-    $DOIT tar czf net-snmp-$VERSION.tar.gz net-snmp-$VERSION
+    # XXX: we should be testing for existance of star first...
+    # gnu tar (as of 1.15.1) is unable to create portable tar archives, 
+    # especially if long file names (>100 char) are present.
+    # star is a better replacement.
+    $DOIT star -Hustar -c -z -f net-snmp-$VERSION.tar.gz net-snmp-$VERSION
     $DOIT md5sum net-snmp-$VERSION.tar.gz > net-snmp-$VERSION.tar.gz.md5
 fi
 
