This commit was manufactured by cvs2svn to create tag 'Ext-5-0-10-pre1'.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/tags/Ext-5-0-10-pre1@12197 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/dist/nsb-functions b/net-snmp/dist/nsb-functions
--- a/net-snmp/dist/nsb-functions
+++ b/net-snmp/dist/nsb-functions
@@ -7,8 +7,11 @@
 #
 # Utility vars
 #
+NSB_BUILD_DIR=${NSB_BUILD_DIR:=""}
+NSB_SRC_DIR=${NSB_SRC_DIR:=""}
+NSB_INSTALL_DIR=${NSB_INSTALL_DIR:=""}
 NSB_QUIET=0
-NSB_PROMPT=1
+NSB_PROMPT=0
 NSB_CLEAN=1
 NSB_CONFIG_ALL=0
 NSB_SKIP_CONFIG=0
@@ -16,42 +19,16 @@ NSB_SKIP_BUILD=0
 NSB_SKIP_TEST=0
 NSB_SKIP_INSTALL=0
 NSB_DIST_TRANSPORTS="UDP TCP Unix"
-NSB_EXTRA_TRANSPORTS="Callback"
-NSB_DIST_MODULES="host disman/event-mib"
-NSB_EXTRA_MODULES="examples examples/example testhandler smux Rmon"
+NSB_EXTRA_TRANSPORTS="Callback UDPIPv6 TCPIPv6 IPX"
+NSB_DIST_MODULES="host disman/event-mib smux"
+NSB_EXTRA_MODULES="examples examples/example testhandler smux Rmon disman/event-mib"
+NSB_EXTRA_CONFIG=${NSB_EXTRA_CONFIG:=""}
 NSB_VIEW=cat
+NSB_SCP=`which scp`
 NSB_PERL=
 #NSB_PERL=--enable-embedded-perl
 NSB_FLOW=
 DATE=`date +%y%m%d_%H%M`
-
-if [ -z $NSB_MAKE ];then
-   echo "Searching for GNU make (set NSB_MAKE to skip this step)"
-   for p in `echo $PATH | tr ':' ' '`
-   do
-      #echo $p
-      if [ -x $p/make ];then
-         dummy=`$p/make --version 2>&1 | grep GNU`
-         if [ $? -eq 0 ];then
-	    echo "using $p/make ($dummy)"
-            NSB_MAKE=$p/make
-            break
-         fi
-      fi
-      if [ -x $p/gmake ];then
-         dummy=`$p/gmake --version 2>&1 | grep GNU`
-         if [ $? -eq 0 ];then
-	    echo "using $p/gmake ($dummy)"
-            NSB_MAKE=$p/gmake
-            break
-         fi
-      fi
-   done
-   if [ -z $NSB_MAKE ];then
-      echo "ERROR: GNU make not found. Set NSB_MAKE to your make executable."
-      exit
-   fi
-fi
 
 #----------------------------------------------------------------------
 #
@@ -60,8 +37,8 @@ fi
 
 nsb-abort()
 {
+   echo
    echo "ABORTING: $@" >&2
-#   echo "last step: $NSB_FLOW" >&2
    exit 255
 }
 
@@ -127,13 +104,15 @@ nsb-config-dist()
    # inside of single quotes, so use double quotes
    #
    echo $ngc_src/configure --with-sys-location=Unknown \
-      --disable-developer \
-      --with-sys-contact='System Administrator' --disable-privacy \
+      --disable-developer $NSB_EXTRA_CONFIG \
+      --with-sys-contact='System Administrator' \
       --with-defaults --with-mib-modules="$NSB_FINAL_MODULES"
    $ngc_src/configure --with-sys-location=Unknown \
-      --disable-developer \
-      --with-sys-contact='System Administrator' --disable-privacy \
+      --disable-developer $NSB_EXTRA_CONFIG \
+      --with-sys-contact='System Administrator' \
       --with-defaults --with-mib-modules="$NSB_FINAL_MODULES"
+   # I'd like to add ' | tee nsb-config.$DATE' to save output, but then
+   # I'd lose the rc from configure, which I need... sigh
    ngc_rc=$?
    if [ $ngc_rc -ne 0 ];then
       nsb-abort "Error during configure dist (rc=$ngc_rc)"
@@ -190,15 +169,17 @@ nsb-config-all()
    # inside of single quotes, so use double quotes
    #
    echo $ngc_src/configure  --with-defaults \
-      --disable-developer \
+      --disable-developer $NSB_EXTRA_CONFIG \
       "--with-mib-modules=$NSB_FINAL_MODULES" \
       "--with-transports=$NSB_DIST_TRANSPORTS $NSB_EXTRA_TRANSPORTS" \
        $NSB_PERL --enable-shared --with-libwrap
    $ngc_src/configure  --with-defaults \
-      --disable-developer \
+      --disable-developer $NSB_EXTRA_CONFIG \
       "--with-mib-modules=$NSB_FINAL_MODULES" \
       "--with-transports=$NSB_DIST_TRANSPORTS $NSB_EXTRA_TRANSPORTS" \
       $NSB_PERL --enable-shared --with-libwrap
+   # I'd like to add ' | tee nsb-config.$DATE' to save output, but then
+   # I'd lose the rc from configure, which I need... sigh
    ngc_rc=$?
    if [ $ngc_rc -ne 0 ];then
       nsb-abort "Error during configure all (rc=$ngc_rc)"
@@ -207,7 +188,7 @@ nsb-config-all()
 
 nsb-sysname()
 {
-   echo `uname -mrs | tr ' /' _`
+   echo `uname -mrs | tr ' /' '__'`
 }
 
 nsb-zip()
@@ -245,6 +226,18 @@ nsb-zip()
    fi
 }
 
+nsb-upload()
+{
+   nsb-flow upload
+   build_dir=$1
+   target=$2
+   dir=$PWD
+   cd $build_dir
+   $NSB_SCP config.log configure-summary nsb-make-all.* \
+                 $target
+   cd $dir
+}
+
 nsb-make()
 {
    nsb-flow make $1
@@ -252,10 +245,40 @@ nsb-make()
    shift 1
    parms=$@
 
+   if [ -z $NSB_MAKE ];then
+      #nsb-info "Searching for GNU make (set NSB_MAKE to skip this step)"
+      for p in `echo $PATH | tr ':' ' '`
+      do
+         #echo $p
+         if [ -x $p/make ];then
+            dummy=`$p/make --version 2>&1 | grep GNU`
+            if [ $? -eq 0 ];then
+	       #nsb-info "using $p/make ($dummy)"
+               NSB_MAKE=$p/make
+               break
+            fi
+         fi
+         if [ -x $p/gmake ];then
+            dummy=`$p/gmake --version 2>&1 | grep GNU`
+            if [ $? -eq 0 ];then
+	       #nsb-info "using $p/gmake ($dummy)"
+               NSB_MAKE=$p/gmake
+               break
+            fi
+         fi
+      done
+      if [ -z $NSB_MAKE ];then
+         nsb-abort "GNU make not found. Set NSB_MAKE to your make executable."
+      fi
+   fi
+
    nsb_make_OUTPUT=nsb-make-$target.$DATE
    nsb-info "Making $target... (log is $nsb_make_OUTPUT)"
-   #$NSB_MAKE touchit 2>&1 | tee $nsb_make_OUTPUT
-   $NSB_MAKE start-flag $target $parms end-flag 2>&1 | tee -a $nsb_make_OUTPUT
+   #
+   if [ "x$target" = "xall" ]; then
+      $NSB_MAKE NOAUTODEPS=y touchit 2>&1 | tee $nsb_make_OUTPUT
+   fi
+   $NSB_MAKE NOAUTODEPS=y start-flag $target $parms end-flag 2>&1 | tee -a $nsb_make_OUTPUT
    # checking $? would only get us the rc from tee, which is useless
 
    nsb-info "Checking for errors..."
@@ -266,7 +289,8 @@ nsb-make()
          > nsb-make-$target-errs.$DATE
    if [ -s nsb-make-$target-errs.$DATE ]; then
       nsb-prompt "press enter to view errors"
-      cat nsb-make-$target-errs.$DATE >&2
+      grep ':' $nsb_make_OUTPUT >&2
+#      cat nsb-make-$target-allerrs.$DATE >&2
       nsb-abort "Error(s) during make $target"
    fi
 
@@ -275,10 +299,23 @@ nsb-make()
    fi
 }
 
+nsb-default-paths()
+{
+   if [ -z "$NSB_SRC_DIR" ]; then
+      NSB_SRC_DIR=$HOME/src/net-snmp-$VERSION
+   fi
+   if [ -z "$NSB_BUILD_DIR" ]; then
+      NSB_BUILD_DIR=$HOME/build
+   fi
+   if [ -z "$NSB_INSTALL_DIR" ]; then
+      NSB_INSTALL_DIR=$NSB_BUILD_DIR/usr/local
+   fi
+}
+
 nsb-build()
 {
    if [ $# -lt 5 ]; then
-      nsb-abort "usage: $0 release src_dir build_directory dest_dir config_all_flag"
+      nsb-abort "usage: $0 release src_dir build_directory dest_dir config_all_flag ($@)"
    fi
 
    nsb_config_all=0
@@ -309,13 +346,16 @@ nsb-build()
    if [ $NSB_CLEAN -gt 0 ]; then
       nsb-info "Cleaning up..."
       if [ $NSB_CLEAN -eq 2 ];then
+        if [ "x$PWD" = "/" ]; then
+           nsb-abort "Not running rm -fR from /"
+        fi
         nsb-info "rm -fR * .[a-zA-Z]* 2>&1 > /dev/null"
         rm -fR * .[a-zA-Z]* 2>&1 > /dev/null
       else
         nsb-info "rm -fR nsb-* $dest_dir 2>&1 > /dev/null"
         rm -fR nsb-* $dest_dir 2>&1 > /dev/null
         if [ -f Makefile ]; then
-            $NSB_MAKE distclean
+            nsb-make NOAUTODEPS=y distclean
             nsb_build_rc=$?
             if [ $nsb_build_rc -ne 0 ]; then
                 nsb-abort "Error during make distclean (rc=$nsb_build_rc)"
@@ -327,9 +367,9 @@ nsb-build()
    if [ $NSB_SKIP_CONFIG -ne 1 ]; then
       nsb-info "Configuring... (log is nsb-config.$DATE)"
       if [ $nsb_config_all -eq 0 ]; then
-          nsb-config-dist $src_dir | tee nsb-config.$DATE
+          nsb-config-dist $src_dir
       else
-          nsb-config-all $src_dir | tee nsb-config.$DATE
+          nsb-config-all $src_dir
       fi
       nsb-prompt "press enter to continue"
    fi
