CHANGES: MinGW: refuse to run the regression tests if kill.exe cannot be found.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@19057 06827809-a52a-0410-b366-d66718629ded

diff --git a/testing/fulltests/support/simple_run b/testing/fulltests/support/simple_run
--- a/testing/fulltests/support/simple_run
+++ b/testing/fulltests/support/simple_run
@@ -23,6 +23,11 @@ if [ "x$srcdir" = "x" ]; then
     fi
 fi
 
+if [ "x$OSTYPE" = "xmsys" -a "x`type -p kill.exe`" = "x" ]; then
+    echo "Error: could not find kill.exe."
+    exit 1
+fi
+
 testscript=$1
 if [ `echo $testscript | cut -c 1-1` != '/' ]; then
     testscript="`pwd`/$1"
