This commit was manufactured by cvs2svn to create tag 'Ext-5-1-3-pre1'.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/tags/Ext-5-1-3-pre1@12375 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/testing/RUNTESTS b/net-snmp/testing/RUNTESTS
--- a/net-snmp/testing/RUNTESTS
+++ b/net-snmp/testing/RUNTESTS
@@ -24,8 +24,8 @@
 usage() { 
     cat << BLIK
 
-Usage: `basename $0` [-a] [-S SLEEPTIME] [-h] [-i] [-v] [-V] [-s]
-       [-T TESTNUMS] [-D bindir] [-S seconds]"
+Usage: `basename $0` [-a] [-S SLEEPTIME] [-h] [-i] [-v] [-V] [-s] [-XM]
+       [-T TESTNUMS] [-D bindir] [-S seconds] [-P <udp|tcp|udp6|tcp6|unix>]"
 
   -a        run all tests.
   -T NUMS   run particular tests (command separated list of numbers)
@@ -36,7 +36,9 @@ Usage: `basename $0` [-a] [-S SLEEPTIME] [-h] [-i] [-v] [-V] [-s]
             response from the agent.
   -A FLAGS  Extra flags to pass to the agent.
   -s        Don't erase the runtime data directory for successful tests
+  -XM       Don't set MIBDIRS environment unless absolutely necessary
   -x        Turn on SH output debugging for tests.
+  -P TRANS  Specify on which transport domain to run the tests.Default is udp.
 
 BLIK
     exit 0
@@ -45,6 +47,8 @@ BLIK
 trap "exit 1;" 1 2 3 9 13 15 17
 
 SNMP_BASEDIR=`dirname $0`
+SNMP_PREFER_NEAR_MIBS=1	## prefer MIB files found in source hierarchy
+export SNMP_PREFER_NEAR_MIBS
 
 ### Check for the configuration script.
 ##if [ ! -s "${SNMP_BASEDIR}/TESTCONF.sh"  ] ; then 
@@ -56,7 +60,7 @@ ORIGDIR=`pwd`		## this script may be invoked with relative path
 SNMP_UPDIR=..		## building from the source tree
 interactive=no
 SNMP_VERBOSE=0
-SNMP_SLEEP=1		## default seconds to sleep
+SNMP_SLEEP=${SNMP_SLEEP:=1} 	## default seconds to sleep
 SH_DEBUG=0
 
 while [ -n "$1" ]; do
@@ -83,6 +87,19 @@ while [ -n "$1" ]; do
 	    shift
 	    SNMP_UPDIR="$1"
 	    ;;
+	-P)
+		shift
+		SNMP_TRANSPORT_SPEC="$1"
+		export SNMP_TRANSPORT_SPEC
+		if [ "x$SNMP_TRANSPORT_SPEC" = "xunix" ];then
+			SNMP_SNMPD_PORT="/var/tmp/unixsnmpd"
+			SNMP_SNMPTRAPD_PORT="/var/tmp/unixsnmptrapd"
+			SNMP_TEST_DEST=""
+			export SNMP_SNMPD_PORT
+			export SNMP_SNMPTRAPD_PORT
+			export SNMP_TEST_DEST
+		fi
+		;;
 	-T)
 	    shift
 	    test_nums=`echo $1 | sed 's/,/ /g'`
@@ -105,6 +122,10 @@ while [ -n "$1" ]; do
 	    SH_DEBUG=1
 	    ;;
 
+	-XM)
+	    SNMP_PREFER_NEAR_MIBS=0
+	    ;;
+
     esac
 
     shift
@@ -112,24 +133,41 @@ done
 
 export SNMP_SLEEP
 
+# Make sure MinGW / MSYS users have the kill.exe program to stop the agent and snmptrapd
+if [ "x$OSTYPE" = "xmsys" ]; then
+  kill_command=`which kill.exe`
+  if [ "x$kill_command" = "x" ]; then
+    echo Could not find kill.exe.  Aborting tests
+    echo Kill.exe is available from the Support Tools package availble on the
+    echo Windows 2000 CDROM under SUPPORT\\TOOLS.
+    exit
+  fi
+fi
+
 # Find executables in source first, then build, then existing PATH.
 ## Add to PATH if a binary is found.
 
 cd $SNMP_UPDIR
 SNMP_UPDIR=`pwd`
 bf=snmpget
-if [ -f "$bf" ] ; then
+if [ -x "$bf" ] ; then
    PATH=$SNMP_UPDIR:$PATH
 else
-   bf=apps/snmpget
-   if [ -f "$bf" ] ; then
-      PATH=$SNMP_UPDIR/apps:$PATH
+  for dd in apps bin ; do
+   bf=$dd/snmpget
+   if [ -x "$bf" ] ; then
+      PATH=$SNMP_UPDIR/$dd:$PATH
+      break
    fi
+  done
 fi
-bf=agent/snmpd
-if [ -f "$bf" ] ; then
-   PATH=$SNMP_UPDIR/agent:$PATH
-fi
+for dd in agent bin sbin ; do
+   bf=$dd/snmpd
+   if [ -x "$bf" ] ; then
+      PATH=$SNMP_UPDIR/$dd:$PATH
+      break
+   fi
+done
 
 bf=include/net-snmp/net-snmp-config.h
 if [ ! -s "$bf" ] ; then
@@ -189,6 +227,24 @@ fi
 rmdir $SNMP_TMPDIR
 unset SNMP_TMPDIR
 export SNMP_TMPDIR
+
+if [ "x$SNMP_PREFER_NEAR_MIBS" = "x0" ]; then
+    # try the compiled MIBDIRS directory first.
+    # if MIB files are not found, fallback to the source base
+
+    snmptranslate -On -IR sysDescr > /dev/null 2>&1
+    if [ $? -ne 0 ] ; then
+        if [ "x$MIBDIRS" = "x" ]; then
+    	MIBDIRS=${SNMP_BASEDIR}/../mibs
+    	export MIBDIRS
+        fi
+    fi
+    snmptranslate -On -IR sysDescr > /dev/null 2>&1
+    if [ $? -ne 0 ] ; then
+        echo "Could not resolve sysDescr in $MIBDIRS. Exiting"
+        exit 1
+    fi
+fi ## SNMP_PREFER_NEAR_MIBS
 
 #
 # Switch to the testing directory, for ease of the client test packages.
