update for new url format in svn entries
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@16429 06827809-a52a-0410-b366-d66718629ded

diff --git a/dist/cvsshow b/dist/cvsshow
--- a/dist/cvsshow
+++ b/dist/cvsshow
@@ -1,7 +1,5 @@
 #!/bin/sh
 #
-# $Id$
-#
 export CVS_RSH=ssh
 TAG=
 
@@ -38,6 +36,13 @@ do_svn()
    fi
 
    ROOT=`grep url $DIR/.svn/entries|cut -f2 -d\"`
+   if [ -z "$ROOT" ]; then
+      ROOT=`grep https $DIR/.svn/entries|head -n 1`
+   fi
+   if [ -z "$ROOT" ]; then
+      echo "Couldn't find root from $DIR/.svn/entries"
+      exit 1
+   fi
 
    echo "Directory $DIR is rooted at $ROOT..."
    echo "   update with svn co $ROOT $DIR"
