sync w/MAIN
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/branches/V5-1-patches@9552 06827809-a52a-0410-b366-d66718629ded

diff --git a/dist/nsb-package b/dist/nsb-package
--- a/dist/nsb-package
+++ b/dist/nsb-package
@@ -42,18 +42,24 @@ usage()
 #
 EXE_PATH=${0%nsb-package}
 EXE_PATH=${EXE_PATH%/}
-if [ -f $EXE_PATH/nsb-functions ];then
-   source $EXE_PATH/nsb-functions
-elif [ -f $HOME/bin/nsb-functions ]; then
-   source $HOME/bin/nsb-functions
-   EXE_PATH=$HOME/bin
-elif [ -f nsb-functions ];then
-   source nsb-functions
-else
-   echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
-   exit 1
+if [ ! -f $EXE_PATH/nsb-functions ];then
+   if [ -f $HOME/bin/nsb-functions ]; then
+      EXE_PATH=$HOME/bin
+   elif [ -f nsb-functions ];then
+      EXE_PATH=$PWD
+   else
+      echo "Cannot find nsb-functions in $EXE_PATH, $HOME/bin or $PWD"
+      exit 1
+   fi
 fi
 
+if [ "x$1" = "x-C" ]; then
+    shift
+else
+    if [ -f $HOME/.snmp/nsb-package ];then
+        source $HOME/.snmp/nsb-package
+    fi
+fi
 
 ########################################################################
 ########################################################################
@@ -88,6 +94,12 @@ if [ $# -ne 1 ]; then
    usage
 fi
 
+NSB_VERSION=$1
+
+source $EXE_PATH/nsb-functions
+
+nsb-default-paths
+
 if [ $NSB_CLEAN -eq 1 ]; then
    if [ $NSB_SKIP_CONFIG -eq 1 ]; then
       echo "A clean build also requires configuration (-d and -c"
@@ -96,29 +108,22 @@ if [ $NSB_CLEAN -eq 1 ]; then
    fi
 fi
 
-VERSION=$1
-
-nsb-default-paths
-
-if [ $NSB_SRC_DIR != $NSB_BUILD_DIR ];then
-   NSB_BUILD_DIR=$NSB_BUILD_DIR/$VERSION-`nsb-sysname`
-fi
-
 
 ########################################################################
 ########################################################################
 nsb-prompt "press enter to build $NSB_SRC_DIR in $NSB_BUILD_DIR, and install in $NSB_INSTALL_DIR"
-nsb-build $VERSION $NSB_SRC_DIR $NSB_BUILD_DIR $NSB_INSTALL_DIR $NSB_CONFIG_ALL
+nsb-build $NSB_VERSION $NSB_SRC_DIR $NSB_BUILD_DIR $NSB_INSTALL_DIR $NSB_CONFIG_ALL
 rc=$?
 if [ ! -z $NSB_SCP_HOST ]; then
-   nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$VERSION-`nsb-sysname`
+   nsb-upload $NSB_BUILD_DIR $NSB_SCP_HOST:$NSB_SCP_DEST/$NSB_VERSION/$NSB_HOST/
 fi
 if [ $rc -eq 0 ] && [ $REMOVE_SUCCESS -eq 1 ];then
     nsb-prompt "press enter to remove $NSB_BUILD_DIR"
     if [ "x$NSB_BUILD_DIR" = "/" ]; then
        nsb-abort "Not running rm -fR from /"
+    else
+       /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
     fi
-    /bin/rm -fR $NSB_BUILD_DIR > /dev/null 2>&1
 fi
 
 nsb-prompt "press enter to exit with rc $RC"
