Made error messages more clear in case of failure or wrong invocation.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@18795 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/testing/fulltests/support/run_olducd b/net-snmp/testing/fulltests/support/run_olducd
--- a/net-snmp/testing/fulltests/support/run_olducd
+++ b/net-snmp/testing/fulltests/support/run_olducd
@@ -1,15 +1,26 @@
 #!/bin/sh
 
+if [ $# = 0 ]; then
+    echo "Usage: $0 <testscript> [<args>]"
+    exit 1
+fi
+
 if [ "x$builddir" = "x" ]; then
     cd ..
     builddir=`pwd`
-    cd testing
+    if ! cd testing; then
+       echo "Error: $0 must be started from inside the testing directory."
+       exit 1
+    fi
 fi
 
 if [ "x$srcdir" = "x" ]; then
     cd ..
     srcdir=`pwd`
-    cd testing
+    if ! cd testing; then
+       echo "Error: $0 must be started from inside the testing directory."
+       exit 1
+    fi
 fi
 
 testscript=$1
