a new nssync() function for push/pulling active branches

diff --git a/local/gittools/shell-functions b/local/gittools/shell-functions
--- a/local/gittools/shell-functions
+++ b/local/gittools/shell-functions
@@ -284,3 +284,22 @@ nsrollup() {
 	echo "  $nsbranchesnotdone"
     fi
 }
+
+nssync() {
+    for branch in $nsbranches ; do
+	git checkout $branch
+	git pull --rebase
+	if [ $? != 0 ] ; then
+	    echo "git pull --rebase failed; please fix first"
+	    return
+	fi
+    done
+    for branch in $nsbranches ; do
+	git checkout $branch
+	git push
+	if [ $? != 0 ] ; then
+	    echo "git push failed; help?"
+	    return
+	fi
+    done
+}
