try a multiple branch push

diff --git a/local/gittools/shell-functions b/local/gittools/shell-functions
--- a/local/gittools/shell-functions
+++ b/local/gittools/shell-functions
@@ -343,12 +343,10 @@ nssync() {
 	    return
 	fi
     done
-    for branch in $nsbranches ; do
-	git checkout $branch
-	git push
-	if [ $? != 0 ] ; then
-	    echo "git push failed; help?"
-	    return
-	fi
-    done
+
+    git push origin $nsbranches
+    if [ $? != 0 ] ; then
+	echo "git push failed; help?"
+	return
+    fi
 }
