added a nsrollup function for rolling branches upward.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@20531 06827809-a52a-0410-b366-d66718629ded

diff --git a/local/gittools/shell-functions b/local/gittools/shell-functions
--- a/local/gittools/shell-functions
+++ b/local/gittools/shell-functions
@@ -108,14 +108,18 @@ nspatchtry() {
     for branch in $nsbranches ; do
 	$nsverbose checking out and applying patch in $branch
 	$nsecho git checkout $branch
-	$nsecho patch "$@"
+
+	$nsverbose Appling patch
+	$nsecho patch --batch "$@"
 	if [ $? = 0 ] ; then
 	    $nsverbose Patch succeeded on $branch
 	    nsgoodbranches="$nsgoodbranches $branch"
 	else
 	    $nsverbose Patch failed on $branch
-	    nsgoodbranches="$nsbadbranches $branch"
+	    nsbadbranches="$nsbadbranches $branch"
 	fi
+
+	$nsverbose cleaning source tree
 	git checkout .
     done
 
@@ -145,6 +149,55 @@ nspatchapply() {
     read ans
 
     if [ $ans = 'y' -o $ans = 'Y' ] ; then
-	$nsecho git commit -a
+	$nsecho git commit -a "$@"
     fi
+}
+
+nsrollup() {
+    _ns_checkclean
+    if [ $NSCLEAN != 1 ]; then
+	return
+    fi
+
+    $nsverbose Pulling all upstream branches
+    $nsecho git pull --all
+    
+    nslastbranch=""
+
+    for branch in $nsbranches ; do
+	if [ "$nslastbranch" != "" ] ; then
+	    $nsverbose checking out $branch
+	    $nsecho git checkout $branch
+
+	    $nsverbose merging $nslastbranch into $branch
+	    $nsecho git merge $nslastbranch
+	    if [ $? != 0 ] ; then
+		echo ""
+		echo "---------------------------------------------"
+		echo "Merge of $nslastbranch into $branch failed!!!"
+		echo ""
+		echo "Hints for fixing this:"
+		echo "  You're on: $branch"
+		echo "  Steps:"
+		echo "    1) fix all files marked as problematic"
+		echo "    2) run 'git add' on each file"
+		echo "    3) run 'git commit' to commit the changes"
+		echo "    4) once done, re-run nsrollup"
+		echo "  Aborting:"
+		echo "    If instead you want to give up, run"
+		echo "    1) git merge --abort"
+		return
+	    fi
+
+	    _ns_checkclean
+	    if [ $NSCLEAN != 1 ] ; then
+		$nsverbose committing merge results
+		$nsecho git commit -m "nsrollup: merging $nslastbranch into $branch" -a
+	    fi
+	fi
+
+	nslastbranch=$branch
+    done
+
+    $nsverbose "Rolled all branches upward"
 }
