This commit was manufactured by cvs2svn to create tag 'Ext-4-2-1-pre1'.
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/tags/Ext-4-2-1-pre1@5066 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/configure b/net-snmp/configure
--- a/net-snmp/configure
+++ b/net-snmp/configure
@@ -5934,7 +5934,7 @@ if test $cross_compiling = yes; then
 EOF
 
   elif test -z $with_endianness; then
-    { echo "configure: error: You are cross-compiling, but you have not specified the target's endianness" 1>&2; exit 1; };
+    { echo "configure: error: You are cross-compiling, but you have not specified the target's endianness" 1>&2; exit 1; }
   fi
 else
   if test $with_endianness; then
