Introduce --with-agentx-socket=FILE configure option. Helps packagers to *properly* customize that path (not encouraged, but quite common).
git-svn-id: file:///home/hardaker/lib/sf-bkups/net-snmp-convert-svnrepo/trunk@14993 06827809-a52a-0410-b366-d66718629ded

diff --git a/net-snmp/configure b/net-snmp/configure
--- a/net-snmp/configure
+++ b/net-snmp/configure
@@ -1142,10 +1142,11 @@ Configuring the agent:
   --with-persistent-directory=\"directory\"
                                   Default directory for persistent data storage.
   --with-persistent-mask=\"mask\"  Default mask for persistent data storage.
-                                    (Default: $default_persistent_mask)
+                                  (Default: 077)
   --with-copy-persistent-files=\"no\" Don't copy persistent files
-                                       (or use \"yes\" to copy them).
-                                       (Default: yes)
+                                     (or use \"yes\" to copy them).
+                                     (Default: yes)
+  --with-agentx-socket=FILE         AgentX socket (Default: /var/agentx/master)
   --with-default-snmp-version=\"3\" Default version of SNMP to use.
                                     (Default: 3)
                                     Legal values: 1, 2 (for SNMPv2c) or 3.
@@ -2773,6 +2774,44 @@ if test "${enable_copy_persistent_files+set}" = set; then
   enableval="$enable_copy_persistent_files"
   { { echo "$as_me:$LINENO: error:  Invalid option. Use --with-copy_persistent_files/--without-copy_persistent_files instead " >&5
 echo "$as_me: error:  Invalid option. Use --with-copy_persistent_files/--without-copy_persistent_files instead " >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+default_agentx_socket="/var/agentx/master"
+
+# Check whether --with-agentx-socket or --without-agentx-socket was given.
+if test "${with_agentx_socket+set}" = set; then
+  withval="$with_agentx_socket"
+
+  if test "$withval" = yes; then
+    { { echo "$as_me:$LINENO: error:  Please provide a full path " >&5
+echo "$as_me: error:  Please provide a full path " >&2;}
+   { (exit 1); exit 1; }; };
+  fi
+  echo "$as_me:$LINENO: result: using AgentX socket $withval" >&5
+echo "${ECHO_T}using AgentX socket $withval" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define AGENTX_SOCKET "$withval"
+_ACEOF
+
+
+else
+
+  echo "$as_me:$LINENO: result: using default AgentX socket $default_agentx_socket" >&5
+echo "${ECHO_T}using default AgentX socket $default_agentx_socket" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define AGENTX_SOCKET "$default_agentx_socket"
+_ACEOF
+
+
+fi;
+# Check whether --enable-agentx-socket or --disable-agentx-socket was given.
+if test "${enable_agentx_socket+set}" = set; then
+  enableval="$enable_agentx_socket"
+  { { echo "$as_me:$LINENO: error:  Invalid option. Use --with-agentx-socket instead " >&5
+echo "$as_me: error:  Invalid option. Use --with-agentx-socket instead " >&2;}
    { (exit 1); exit 1; }; }
 fi;
 
@@ -5225,7 +5264,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5228 "configure"' > conftest.$ac_ext
+  echo '#line 5267 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6722,7 +6761,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6725:" \
+echo "$as_me:6764:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7760,10 +7799,6 @@ _lt_linker_boilerplate=`cat conftest.err`
 $rm conftest*
 
 
-## CAVEAT EMPTOR:
-## There is no encapsulation within the following macros, do not change
-## the running order or otherwise move them around unless you know exactly
-## what you are doing...
 
 lt_prog_compiler_no_builtin_flag=
 
@@ -7789,11 +7824,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7792: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7827: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7796: \$? = $ac_status" >&5
+   echo "$as_me:7831: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8057,11 +8092,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8060: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8095: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8064: \$? = $ac_status" >&5
+   echo "$as_me:8099: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8161,11 +8196,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8164: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8199: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8168: \$? = $ac_status" >&5
+   echo "$as_me:8203: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10506,7 +10541,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10509 "configure"
+#line 10544 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10606,7 +10641,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10609 "configure"
+#line 10644 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12513,10 +12548,6 @@ test "$ld_shlibs_CXX" = no && can_build_shared=no
 GCC_CXX="$GXX"
 LD_CXX="$LD"
 
-## CAVEAT EMPTOR:
-## There is no encapsulation within the following macros, do not change
-## the running order or otherwise move them around unless you know exactly
-## what you are doing...
 
 cat > conftest.$ac_ext <<EOF
 class Foo
@@ -12950,11 +12981,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12953: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12984: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12957: \$? = $ac_status" >&5
+   echo "$as_me:12988: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13054,11 +13085,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13057: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13088: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13061: \$? = $ac_status" >&5
+   echo "$as_me:13092: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14624,11 +14655,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14627: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14631: \$? = $ac_status" >&5
+   echo "$as_me:14662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14728,11 +14759,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14731: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14762: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14735: \$? = $ac_status" >&5
+   echo "$as_me:14766: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16906,10 +16937,6 @@ archive_cmds_need_lc_GCJ=no
 
 old_archive_cmds_GCJ=$old_archive_cmds
 
-## CAVEAT EMPTOR:
-## There is no encapsulation within the following macros, do not change
-## the running order or otherwise move them around unless you know exactly
-## what you are doing...
 
 lt_prog_compiler_no_builtin_flag_GCJ=
 
@@ -16935,11 +16962,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16938: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16965: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16942: \$? = $ac_status" >&5
+   echo "$as_me:16969: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17203,11 +17230,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17206: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17233: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17210: \$? = $ac_status" >&5
+   echo "$as_me:17237: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17307,11 +17334,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17310: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17337: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17314: \$? = $ac_status" >&5
+   echo "$as_me:17341: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
